### PR TITLE
Reduced 10xdev.cc to 387B

### PR DESCRIPTION
**Pull request by m4r-v1n**
optimized everything (once again:)

thank you for the awesome 1kb.club project!

bloat is our enemy :)

### CODE REVIEW

**Comment by bradleytaunt** [comment]
I am consistently getting `403`  -> https://gtmetrix.com/reports/10xdev.cc/chPnpmiR/

**Comment by m4r-v1n** [comment]
Well, it shows "Total Page Size - 403B" @ Page Details, yes 🤷‍♂️
Not sure where it comes from... 

But the actual page size is 374B.

```
$ curl --head https://10xdev.cc/
HTTP/2 200
server: nginx
date: Sat, 10 Sep 2022 16:30:44 GMT
content-type: text/html; charset=utf-8
content-length: 374
accept-ranges: bytes
```

`gtmetrix` also shows 374B in Waterfall tab:

Screenshot 2022-09-10 at 19 34 02

So, should I use 403 or 374?

**Comment by bradleytaunt** [comment]
403 since we use GTMetrix as the main source (keep things consistent)

**Comment by raregems-io** [comment]
FYI, I removed `<link rel=icon href=data:,>` and just dropping `/favicon.ico` request on the server-side :)

**Comment by raregems-io** [comment]
BTW, according to gtmetrix, `1kb.lingdocs.com` is 710B, not 500B

**Comment by m4r-v1n** [comment]
updated nginx gzip config, now gtmetrix consistently shows 387B

Screenshot 2022-09-10 at 20 03 54

**Pull request merged**
