### PR TITLE
Add pussthecat.org/1

### PR DESCRIPTION
**Pull request by TheFrenchGhosty**

### CODE REVIEW

**Comment by bradleytaunt** [comment]
Sorry but I am getting `4.92kB` -> https://gtmetrix.com/reports/pussthecat.org/bXfKWjD5/

**Comment by TheFrenchGhosty** [comment]
@bradleytaunt It's the favicon that their browser automatically pull... The actual html is 815 bytes: https://github.com/PussTheCat-org/PussTheCat.org/blob/master/public/1/index.html

Also, you can ask me instead of instantly closing the PR...

**Comment by bradleytaunt** [comment]
@TheFrenchGhosty The closing of the PR wasn't meant to be rude - sorry if it came off that way!

Unfortunately the weight of the favicon is taken into account for page size - since it is requested by the browser. A good way to avoid that is setting it as a `data-type`

**Comment by TheFrenchGhosty** [comment]
@bradleytaunt Done.

Do you want me to use the size from gtmetrix (565 Bytes) or the actual HTML size (849 Bytes)?

**Comment by bradleytaunt** [comment]
The `643` from the gt score should be fine! https://gtmetrix.com/reports/pussthecat.org/VTFLYkrO/

**Comment by TheFrenchGhosty** [comment]
@bradleytaunt Should I use the size of the redirect or the size of the actual page?

/1 = 79 Bytes more https://gtmetrix.com/reports/pussthecat.org/VTFLYkrO/

/1/ = just the HTML https://gtmetrix.com/reports/pussthecat.org/SCUo3M09/

I used /1 in the markdown because that's how you did it for the others, but it's technically just a redirect (I guess I can use /1/ instead).

**Comment by bradleytaunt** [comment]
@TheFrenchGhosty It is fine to use the `/1/` number (`565`) but keep it as `/1` for simplicity :+1:

**Comment by TheFrenchGhosty** [comment]
@bradleytaunt Done.

**Pull request merged**
